name: Deploy to Local Machine

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up SSH and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 127.0.0.1
          username: ${{ secrets.USERNAME }}  # Store your Windows username as a GitHub Secret
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}  # The SSH private key
          script: |
            cd /c/xampp/htdocs/test/github
            git pull origin main
