name: Deploy to Local Machine

on:
  push:
    branches:
      - main  # Trigger this action on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can use any runner, but 'ubuntu-latest' is a good choice

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up SSH for local machine
        uses: appleboy/ssh-action@v0.1.5  # Use the latest version of the SSH action
        with:
          host: ff098ddfaf33e6.lhr.life  # Use the public URL from localhost.run
          username: ${{ secrets.USERNAME }}  # Add your local username as a secret
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}  # The SSH key added as a secret
          port: 22  # SSH port (default is 22)

      - name: Pull latest code on local machine
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@f4c4625b3c6126.lhr.life 'cd /c/xampp/htdocs/test/github && git pull origin main'  # Adjust path for Windows compatibility
