name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Use the latest version of the checkout action

      - name: Deploy Application
        run: |
          # Change to the directory where your project is located
          cd C:/xampp/htdocs/test/github  # Make sure the path is correct

          # Pull the latest updates from the repository
          git pull origin staging

          # Add additional deployment steps here (e.g., build, restart services)
