name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, vm-machine]

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "jezraelsalino@gmail.com"
          git config --global user.name "JezraelSalino"

      - name: Pull Latest Changes
        run: |
          cd C:/Users/Jezmahboi/Projects/github  # Ensure this is the correct project path
          git pull origin main

      # Add additional deployment steps if needed
