name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
         cd C:/xampp/htdocs/test/github

        git pull origin staging

      # Add additional deployment steps here (e.g., build, restart services)
