name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, vm-machine]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Use the latest version of the checkout action

      - name: Deploy Application
        run: |
          cd C:/Users/Jezmahboi/Projects/github  # Project path

          git config --global user.email "jezraelsalino@gmail.com"
          git config --global user.name "JezraelSalino"

          # Pull the latest updates from the repository for example
          git pull origin main

          # Add additional deployment steps here (e.g., build, restart services)
