name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "jezraelsalino@gmail.com"
        git config --global user.name "JezraelSalino"

    - name: Pull latest updates
      run: git pull origin staging
